package com.librestatic.lightforge.core.model

import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.nio.ByteBuffer
import java.util.Base64
import org.junit.Assert.*
import org.junit.Test

class PortablePhotoRecipeTest {
    private val sourceId = "00000000-0000-0000-0000-000000000001"

    private fun id(n: Int) = "00000000-0000-0000-0000-${n.toString().padStart(12,'0')}"

    private fun source(id: String = sourceId) =
        PortableSourceFacts(
            id,
            "a".repeat(64),
            10,
            PortableMediaKind.Image,
            100,
            99,
            true,
            "Pictures/été/",
        )

    private fun snapshot() =
        PortableOrganizationSnapshot(
            snapshotId = id(2),
            originNamespace = id(3),
            createdAtMillis = 42,
            scope = PortableOrganizationScope(1, 1, 0),
            sources = listOf(source()),
            preferencesJsonForReview = "{\"schemaVersion\":5}",
        )

    private fun recipe(operations: List<String> = listOf("flip,h")) =
        PortablePhotoRecipe(sourceId, 2, 10, 20, operations)

    private fun reject(block: () -> Unit) {
        try {
            block()
        } catch (expected: Exception) {
            return
        }
        fail("Invalid portable recipe accepted")
    }

    private val operations =
        listOf(
            EditOperation.Crop(10, 20, 980, 990),
            EditOperation.Rotate(270),
            EditOperation.Flip(false),
            EditOperation.Straighten(-4.5f),
            EditOperation.Tone(.2f, 1.5f, .7f),
            EditOperation.Filter("vivid"),
            EditOperation.RawDevelop(
                RawDevelopmentSettings(
                    exposureEv = 1.25f,
                    temperatureKelvin = 5500,
                    tint = -15f,
                    highlights = -.2f,
                    shadows = .3f,
                    whites = -.1f,
                    blacks = .15f,
                    contrast = .25f,
                    saturation = .5f,
                    vibrance = .6f,
                    highlightRecovery = .8f,
                    luminanceNoiseReduction = .1f,
                    chromaNoiseReduction = .2f,
                    sharpening = .4f,
                    chromaticAberrationCorrection = false,
                    lensCorrection = true,
                )
            ),
        )

    @Test
    fun versionTwoRoundTripsEveryKnownOperationIncludingRawAndCountsThem() {
        val expected =
            snapshot()
                .copy(
                    schemaVersion = 2,
                    photoRecipes = listOf(recipe(operations.map(EditOperationCodec::encode))),
                )
        val restored = PortableOrganizationCodec.decode(PortableOrganizationCodec.encode(expected))
        assertEquals(expected, restored)
        assertEquals(
            operations,
            restored.photoRecipes.single().operations.map(EditOperationCodec::decode),
        )
        assertEquals(1, restored.totals().entities)
        assertEquals(operations.size.toLong(), restored.totals().relationships)
        assertEquals(1, restored.totals().reviewOnlyItems)
    }

    @Test
    fun versionOneExactGoldenBytesFromUnmodifiedBaselineStayCompatible() {
        // Generated by the pre-change model.jar; command/source/hash retained in wave35 evidence.
        val bytes =
            Base64.getDecoder()
                .decode(
                    "VUdPUkcBDQoAAAABAAAAJDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMgAAACQwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDMAAAAAAAAAKgAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAQAAACQwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEAAABAYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQAAAAAAAAAKAAAAAAAAAAAAAABkAQAAAAAAAABjAQEAAAAPUGljdHVyZXMvw6l0w6kvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABN7InNjaGVtYVZlcnNpb24iOjV9"
                )
        assertArrayEquals(bytes, PortableOrganizationCodec.encode(snapshot()))
        val restored = PortableOrganizationCodec.decode(bytes)
        assertEquals(snapshot(), restored)
        assertEquals(1, restored.schemaVersion)
        assertTrue(restored.photoRecipes.isEmpty())
        assertArrayEquals(bytes, PortableOrganizationCodec.encode(restored))
        reject { snapshot().copy(photoRecipes = listOf(recipe())).validate() }
        reject { PortableOrganizationCodec.decode(bytes + byteArrayOf(0, 0, 0, 0)) }
    }

    @Test
    fun equalDigestInstancesRetainDifferentRecipeOrdersAndRevisions() {
        val second = id(4)
        val firstRecipe = recipe(listOf("flip,h", "rotate,90"))
        val secondRecipe =
            recipe(listOf("rotate,90", "flip,h")).copy(sourceId = second, revision = 40)
        val expected =
            snapshot()
                .copy(
                    schemaVersion = 2,
                    scope = PortableOrganizationScope(2, 2, 0),
                    sources = listOf(source(), source(second)),
                    photoRecipes = listOf(firstRecipe, secondRecipe),
                )
        val restored = PortableOrganizationCodec.decode(PortableOrganizationCodec.encode(expected))
        assertEquals(expected, restored)
        assertNotEquals(restored.photoRecipes[0], restored.photoRecipes[1])
        assertEquals(2, restored.totals().entities)
        assertEquals(4L, restored.totals().relationships)
    }

    @Test
    fun sourceKindIdentityAndRecipeMetadataAreValidated() {
        val valid = snapshot().copy(schemaVersion = 2, photoRecipes = listOf(recipe()))
        reject { valid.copy(photoRecipes = listOf(recipe(), recipe())).validate() }
        reject { valid.copy(photoRecipes = listOf(recipe().copy(sourceId = id(9)))).validate() }
        reject {
            valid.copy(sources = listOf(source().copy(kind = PortableMediaKind.Video))).validate()
        }
        reject {
            valid
                .copy(sources = listOf(source().copy(kind = PortableMediaKind.Document)))
                .validate()
        }
        listOf(
                recipe().copy(revision = -1),
                recipe().copy(createdAtMillis = -1),
                recipe().copy(updatedAtMillis = 9),
                recipe().copy(sourceId = "foreign:key:9"),
            )
            .forEach { invalid -> reject { valid.copy(photoRecipes = listOf(invalid)).validate() } }
        assertEquals(valid, valid.validate())
        assertTrue(
            valid
                .copy(photoRecipes = listOf(recipe(emptyList())))
                .validate()
                .photoRecipes
                .single()
                .operations
                .isEmpty()
        )
    }

    @Test
    fun noncanonicalFlagsVersionsExtraColumnsAndNumberSpellingsReject() {
        val raw = EditOperationCodec.encode(operations.last())
        val invalid =
            listOf(
                "flip,other",
                "flip,h,extra",
                "rotate,090",
                "rotate,90,extra",
                "crop,0,0,1000,1000,extra",
                "straighten,1",
                "tone,0,1,1",
                "tone,0.0,1.0,1.0,extra",
                "filter,mono,extra",
                " filter,mono",
                raw.replace("raw,1,", "raw,2,"),
                raw.substringBeforeLast(',') + ",2",
                raw + ",extra",
            )
        invalid.forEach { encoded -> reject { recipe(listOf(encoded)).validate() } }
        // Valid canonical alternatives are accepted rather than banning legitimate operations.
        listOf(
                "flip,h",
                "flip,v",
                "rotate,-90",
                "straighten,1.0",
                "tone,0.0,1.0,1.0",
                "filter,mono",
                raw,
            )
            .forEach { recipe(listOf(it)).validate() }
    }

    @Test
    fun unknownOperationsInvalidRangesAndOversizedUtf8Reject() {
        val invalid =
            listOf(
                "exec,anything",
                "crop,0,0,0,1000",
                "rotate,91",
                "straighten,NaN",
                "straighten,Infinity",
                "straighten,46.0",
                "tone,2.0,1.0,1.0",
                "filter,remote",
                "filter," + "é".repeat(510),
                "x".repeat(1025),
            )
        invalid.forEach { reject { recipe(listOf(it)).validate() } }
        val valid = snapshot().copy(schemaVersion = 2, photoRecipes = listOf(recipe()))
        reject {
            PortableOrganizationCodec.encode(
                valid.copy(photoRecipes = listOf(recipe(List(501) { "flip,h" })))
            )
        }
    }

    @Test
    fun operationAggregateLimitsAndEntityTotalsIncludeRecipes() {
        val ids = (1..200).map(::id)
        val full =
            snapshot()
                .copy(
                    schemaVersion = 2,
                    scope = PortableOrganizationScope(200, 200, 0),
                    sources = ids.map(::source),
                    photoRecipes = ids.map { recipe(List(500) { "flip,h" }).copy(sourceId = it) },
                )
        assertEquals(100000L, full.totals().relationships)
        assertEquals(full, PortableOrganizationCodec.decode(PortableOrganizationCodec.encode(full)))
        val more = id(201)
        reject {
            full
                .copy(
                    scope = PortableOrganizationScope(201, 201, 0),
                    sources = full.sources + source(more),
                    photoRecipes = full.photoRecipes + recipe().copy(sourceId = more),
                )
                .validate()
        }
        val entityFull =
            snapshot()
                .copy(
                    schemaVersion = 2,
                    photoRecipes = listOf(recipe()),
                    people =
                        List(PortableOrganizationSnapshot.MaximumEntities) {
                            PortablePersonIdentity(id(it + 10), null, "v1")
                        },
                )
        reject { entityFull.validate() }
        reject {
            snapshot()
                .copy(
                    schemaVersion = 2,
                    photoRecipes =
                        List(PortableOrganizationSnapshot.MaximumSources + 1) { recipe() },
                )
                .validate()
        }
    }

    @Test
    fun versionTwoTruncationTrailingDataAndUnknownVersionsReject() {
        val bytes =
            PortableOrganizationCodec.encode(
                snapshot()
                    .copy(
                        schemaVersion = 2,
                        photoRecipes = listOf(recipe(operations.map(EditOperationCodec::encode))),
                    )
            )
        for (length in bytes.indices) reject {
            PortableOrganizationCodec.decode(bytes.copyOf(length))
        }
        reject { PortableOrganizationCodec.decode(bytes + byteArrayOf(1)) }
        for (version in listOf(-1, 0, 5, Int.MAX_VALUE)) reject {
            PortableOrganizationCodec.decode(
                bytes.copyOf().also { ByteBuffer.wrap(it, 8, 4).putInt(version) }
            )
        }
        reject { snapshot().copy(schemaVersion = 5).validate() }
    }

    @Test
    fun wireCountsStringsUtf8AndNoncanonicalOperationsFailBeforeAcceptance() {
        val prefix =
            PortableOrganizationCodec.encode(snapshot().copy(schemaVersion = 2))
                .dropLast(4)
                .toByteArray()
        fun wire(
            count: Int = 1,
            operationCount: Int = 1,
            encoded: ByteArray = "flip,h".toByteArray(),
            length: Int = encoded.size,
        ): ByteArray {
            val tail = ByteArrayOutputStream()
            DataOutputStream(tail).use { out ->
                out.writeInt(count)
                if (count == 1) {
                    val id = sourceId.toByteArray()
                    out.writeInt(id.size)
                    out.write(id)
                    out.writeInt(0)
                    out.writeLong(0)
                    out.writeLong(0)
                    out.writeInt(operationCount)
                    if (operationCount == 1) {
                        out.writeInt(length)
                        out.write(encoded)
                    }
                }
            }
            return prefix + tail.toByteArray()
        }
        assertEquals(
            "flip,h",
            PortableOrganizationCodec.decode(wire()).photoRecipes.single().operations.single(),
        )
        listOf(
                wire(count = -1),
                wire(count = 10001),
                wire(operationCount = -1),
                wire(operationCount = 501),
                wire(length = 1025),
                wire(length = -1),
                wire(encoded = byteArrayOf(0xc3.toByte(), 0x28)),
                wire(encoded = "flip,wrong".toByteArray()),
            )
            .forEach { bytes -> reject { PortableOrganizationCodec.decode(bytes) } }
    }
}
