package com.librestatic.lightforge.feature.semanticsearch

import android.app.ActivityManager
import android.content.Context
import android.os.Build
import java.io.File

enum class SemanticModelCompatibility { Recommended, Supported, TechnicallyUnsupported }

data class SemanticModelDescriptor(
    val id: String,
    val displayName: String,
    val version: String,
    val packageUrl: String,
    val packageBytes: Long,
    val packageSha256: String,
    val signatureBase64: String,
    val minimumRamMb: Int,
    val recommendedRamMb: Int,
    val embeddingDimensions: Int = 512,
) {
    init {
        require(id.matches(Regex("[a-z0-9-]+")))
        require(packageUrl.startsWith("https://github.com/LibreStatic/lightforge-models/releases/download/"))
        require(packageBytes > 0)
        require(packageSha256.matches(Regex("[a-f0-9]{64}")))
        require(signatureBase64.isNotBlank())
        require(embeddingDimensions == CompactSemanticEmbedding.Dimensions)
    }
}

object SemanticModelCatalog {
    // Values are generated by tools/semantic-models/build_packages.py. Model packages are
    // immutable release assets; changing any artifact requires a new descriptor version.
    val models: List<SemanticModelDescriptor> = listOf(
        SemanticModelDescriptor(
            id = "tinyclip-balanced",
            displayName = "TinyCLIP Balanced",
            version = "1.0.0",
            packageUrl = "https://github.com/LibreStatic/lightforge-models/releases/download/semantic-models-v1/tinyclip-balanced-1.0.0.ugmodel",
            packageBytes = 63_025_902,
            packageSha256 = "00d596e3b425074ab5b6f0e9f4d02bc641fffcb20c2b737c037321dbf590063c",
            signatureBase64 = "MEYCIQCJWI2zU6e3vDXqg1Mrw3v0soXBl0pU24uX/WwpVmuyQgIhAPdkktj8Ch02ye6nKxu2gpvSNjhzY4qCeQ4KF0ghXRXV",
            minimumRamMb = 3_072,
            recommendedRamMb = 4_096,
        ),
        SemanticModelDescriptor(
            id = "tinyclip-quality",
            displayName = "TinyCLIP Quality",
            version = "1.0.0",
            packageUrl = "https://github.com/LibreStatic/lightforge-models/releases/download/semantic-models-v1/tinyclip-quality-1.0.0.ugmodel",
            packageBytes = 236_800_015,
            packageSha256 = "82f77cdc4419c40bc8d18105d46b44cea745b63791ed62c6de7c34ce60bcace2",
            signatureBase64 = "MEQCICVo5YtXnFP2XwUaYVCGj2qj6xKys0cvGH6D9kHtHmpoAiB8T7O0du45QIJmm/1BVXq93BC6gKC/lPkvX8I/SEV/PA==",
            minimumRamMb = 6_144,
            recommendedRamMb = 8_192,
        ),
    )
}

data class SemanticHardwareProfile(
    val totalRamMb: Int,
    val supportedAbis: List<String>,
)

object SemanticModelSelector {
    fun profile(context: Context): SemanticHardwareProfile {
        val memory = ActivityManager.MemoryInfo()
        context.getSystemService(ActivityManager::class.java).getMemoryInfo(memory)
        return SemanticHardwareProfile(
            totalRamMb = (memory.totalMem / (1024L * 1024L)).toInt(),
            supportedAbis = Build.SUPPORTED_ABIS.toList(),
        )
    }

    fun compatibility(model: SemanticModelDescriptor, profile: SemanticHardwareProfile): SemanticModelCompatibility {
        if (profile.supportedAbis.none { it == "arm64-v8a" || it == "x86_64" } ||
            profile.totalRamMb < model.minimumRamMb
        ) return SemanticModelCompatibility.TechnicallyUnsupported
        return if (profile.totalRamMb >= model.recommendedRamMb) {
            SemanticModelCompatibility.Recommended
        } else {
            SemanticModelCompatibility.Supported
        }
    }

    fun recommended(models: List<SemanticModelDescriptor>, profile: SemanticHardwareProfile): SemanticModelDescriptor? =
        models.filter { compatibility(it, profile) != SemanticModelCompatibility.TechnicallyUnsupported }
            .maxByOrNull { model ->
                val preferred = compatibility(model, profile) == SemanticModelCompatibility.Recommended
                (if (preferred) 1_000_000 else 0) + model.recommendedRamMb
            }
}

data class InstalledSemanticModel(
    val descriptor: SemanticModelDescriptor,
    val directory: File,
) {
    val imageModel: File get() = directory.resolve("image.tflite")
    val textModel: File get() = directory.resolve("text.tflite")
    val vocabulary: File get() = directory.resolve("vocab.json")
    val merges: File get() = directory.resolve("merges.txt")
}
